version: '3'
services:
  swasm:
    image: ghcr.io/swiftwasm/carton:latest
    command: bash
    volumes: [.:/code]
    ports: [8080:8080]
    container_name: carton
    working_dir: /code
    tty: true
    stdin_open: true
