name: Build and deploy

on: [pull_request, workflow_dispatch]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    container: ghcr.io/swiftwasm/carton:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build site files
      run: |
        ./do.sh build
      env:
        JEKYLL_ENV: production
    - name: Push to pages branch
      uses: Sammcb/push-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        paths: Bundle/*
